notifications:
  email: false

language: php

php:
  - 7.2

env:
  matrix:
    - TYPO3_VERSION=~9.5

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/minimal="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - npm install -g grunt-cli

script:

  - >
    echo;
    echo "Install NPM dependencies";
    cd felayout_t3kit/ && npm install

  - >
    echo;
    echo "Running grunt lessCompile";
    grunt compileLess
